### PR TITLE
rewrite of recipe in reponse to review comments

### LINKED ISSUE #8: anaconda upload failing with 'file does not exist'
`anaconda upload` from both CircleCI and TravisCI is failing for the new release with errors like this [[ref](https://circleci.com/gh/conda-forge/lal-feedstock/22), [ref](https://travis-ci.org/conda-forge/lal-feedstock/builds/433379714)]:

```
[ERROR] File "/home/conda/feedstock_root/build_artifacts/linux-64/lal-6.19.0-hee24be8_0.tar.bz2" does not exist
Traceback (most recent call last):
  File "/opt/conda/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/build_utils.py", line 82, in upload_package
    upload_or_check(recipe_root, owner, channel, [config_file])
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 135, in upload_or_check
    upload(token_fn, path, owner, channel)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 65, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/tmp/tmptxtgcqgp/binstar.token', 'upload', '/home/conda/feedstock_root/build_artifacts/linux-64/lal-6.19.0-hee24be8_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
Exited with code 1
```

cc: @conda-forge/core - help is greatly appreciated.

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR introduces a rewrite of the recipe in response to review comments from @isuruf (thanks!). The main changes are

- build just the C library and the SWIG interface in the outer build
- for the `lal` output, just run `make install`
- for each of the `python-lal` outputs, reconfigure to build _only_ the python bindings, then install only what we want

This should simplify (shorten) the build, and hopefully fix #8, since the `lal` package is only built once.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@isuruf, I have attempted to follow your advice and use `scripts` in the output. However, both [the linux build](https://circleci.com/gh/conda-forge/lal-feedstock/33) and [the macOS build](https://travis-ci.org/conda-forge/lal-feedstock/builds/434144915) are failing for _different_ reasons I can't understand. Any help you can give would be (again) greatly appreciated.

I think @skymoo might be able to help with the macOS failure at least.

**Comment by duncanmmacleod** [comment]
@conda-forge/core, can somebody comment on likely causes of this error ([ref](https://circleci.com/gh/conda-forge/lal-feedstock/35)):

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/python-lal-6.19.0-py35h7eb728f_1.tar.bz2
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'python-lal==6.19.0=py35h7eb728f_1'}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'python-lal==6.19.0=py35h7eb728f_1'}
Tests failed for python-lal-6.19.0-py35h7eb728f_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for python-lal-6.19.0-py35h7eb728f_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: python-lal-6.19.0-py35h7eb728f_1.tar.bz2
```

I can reproduce this outside of CI, but don't understand how to debug. Any help is greatly appreciated.

**Comment by scopatz** [comment]
@duncanmmacleod - It seems that one of your upstream dependencies is not available for whichever platform you are building for.  conda(-build)'s error messages aren't great here.  But since this is happening in the tests, it is probably one of the test dependencies

**Comment by duncanmmacleod** [comment]
@scopatz! I think I just got caught out by `dateutil` vs `python-dateutil`. It was staring me in the face the whole time. Grrr.

**Comment by duncanmmacleod** [comment]
@conda-forge/core, I would be very appreciative of a review of this updated recipe. @ocefpaf suggested that it be re-written to use install scripts, rather than file selection.

I haven't gotten the hang of how to access the build and host environments in the install scripts (packaging step?), but hopefully things aren't too hacky.

**Pull request merged**
